#!/usr/bin/env bash
# Display domain or subdomain information
dinfo () {
    rtype=$(dig $2.$1 | awk '/ANSWER SECTION:/ {getline;print}' | cut -d$'\t' -f 3)
    webip=$(dig $2.$1 | awk '/ANSWER SECTION:/ {getline;print}' | cut -d$'\t' -f 4)
    echo "The subdomain $2 is a $rtype record and points to $webip"
}
if [ $# -eq 1 ]; then
    dinfo "$1" "www"
    dinfo "$1" "lb-01"
    dinfo "$1" "web-01"
    dinfo "$1" "web-02"
else
    dinfo "$1" "$2"
fi
