#!/usr/bin/env bash
# Configure NGINX
apt-get -y update
apt-get -y install haproxy
config="
frontend front_server
	 bind *:80
	 mode http
	 default_backend back_server

backend back_server
	balance roundrobin
	server 1200-web-01 35.237.254.152:80 check
	server 1200-web-02 35.196.237.181:80 check
"
echo "$config" >> /etc/haproxy/haproxy.cfg
service haproxy restart
