#!/usr/bin/env bash
# Displays its own PID
touch /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
function sigterm_handler()
{
    echo "I hate the kill command"
    rm /var/run/holbertonscript.pid
    exit
}
function sigquit_handler()
{
    rm /var/run/holbertonscript.pid
    exit
}
trap 'echo "Y U no love me?!"' SIGINT
trap sigterm_handler SIGTERM
trap sigquit_handler SIGQUIT
while true; do
	echo "To infinity and beyond"
	sleep 2
done
